// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection — a PgBouncer-style
    // pooler in front of DATABASE_URL doesn't support the advisory lock
    // `prisma migrate` takes. DATABASE_URL_UNPOOLED is only set in
    // production/preview (Vercel + Neon); local dev has no pooler, so
    // DATABASE_URL is the correct fallback there.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
